# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

negloglik_overall <- function(arg, z, trunc_lower, trunc_upper, p0) {
    .Call(`_EmpiNull_negloglik_overall`, arg, z, trunc_lower, trunc_upper, p0)
}

negloglik_individualized <- function(arg, z, n, trunc_lower, trunc_upper, p0) {
    .Call(`_EmpiNull_negloglik_individualized`, arg, z, n, trunc_lower, trunc_upper, p0)
}

negloglik_confounder <- function(arg, z, x_bar, n, trunc_lower, trunc_upper, p0) {
    .Call(`_EmpiNull_negloglik_confounder`, arg, z, x_bar, n, trunc_lower, trunc_upper, p0)
}

negloglik_confounder_gs <- function(arg, z, x_bar, n, trunc_lower, trunc_upper, p0, phi) {
    .Call(`_EmpiNull_negloglik_confounder_gs`, arg, z, x_bar, n, trunc_lower, trunc_upper, p0, phi)
}

negloglik_confounder_CRE <- function(arg, z, n, trunc_lower, trunc_upper, p0) {
    .Call(`_EmpiNull_negloglik_confounder_CRE`, arg, z, n, trunc_lower, trunc_upper, p0)
}

negloglik_pois2 <- function(theta, z, Xbar, E, E2, trunc_lower, trunc_upper, p0) {
    .Call(`_EmpiNull_negloglik_pois2`, theta, z, Xbar, E, E2, trunc_lower, trunc_upper, p0)
}

